bitcoind:
  #build: .
  #dockerfile: Dockerfile
  image: christroutner/bitcoind-bch-abc-0.21.9
  container_name: bitcoind
  ports:
    - "8332:8332"   # RPC mainnet port
    - "8333:8333"   # p2p mainnet port
    - "28332:28332" # ZMQ port
  volumes:
#    - ../blockchain-data/bch-mainnet-abc:/data
    - /mnt/data/bitcoin.com/blockchain-data/bch-mainnet-abc:/data
    - ../config:/home/bitcoin/config
  restart: always
